'use strict';
const loader=document.getElementById('loader'),floatersEl=document.getElementById('floaters'),musicBtn=document.getElementById('musicBtn'),ctaBtn=document.getElementById('ctaBtn'),cardWrapper=document.getElementById('cardWrapper'),card=document.getElementById('card'),confettiCvs=document.getElementById('confettiCanvas'),ctx=confettiCvs.getContext('2d');
let musicPlaying=false,cardFlipped=false,confettiActive=false,confettiPcs=[],animFrame,audioCtx=null;
window.addEventListener('load',()=>{setTimeout(()=>{loader.classList.add('fade-out');setTimeout(()=>{loader.style.display='none';initFloaters();animateHeroEntrance();},800);},2000);});
const floaterDefs=[
{type:'heart',count:10,svg:(c)=>`<svg viewBox="0 0 30 28" fill="none"><path d="M15 26C15 26 2 18 2 9.5C2 6.46 4.46 4 7.5 4C9.24 4 10.91 4.85 12 6.08C13.09 4.85 14.76 4 16.5 4C19.54 4 22 6.46 22 9.5C22 18 15 26 15 26Z" fill="${c}" opacity="0.8"/></svg>`,colors:['#f48fb1','#e91e63','#fce4ec','#f06292','#f8bbd0'],sizeRange:[18,36]},
{type:'star',count:8,svg:(c)=>`<svg viewBox="0 0 30 30" fill="none"><path d="M15 3L17.5 12H27L19.5 17.5L22 27L15 21.5L8 27L10.5 17.5L3 12H12.5L15 3Z" fill="${c}" opacity="0.75"/></svg>`,colors:['#f8bbd0','#f48fb1','#fce4ec','#e91e63'],sizeRange:[14,28]},
{type:'sparkle',count:10,svg:(c)=>`<svg viewBox="0 0 30 30" fill="none"><path d="M15 2L16.5 13.5L28 15L16.5 16.5L15 28L13.5 16.5L2 15L13.5 13.5Z" fill="${c}" opacity="0.7"/></svg>`,colors:['#f48fb1','#fce4ec','#f8bbd0','#fff9fb'],sizeRange:[10,22]},
{type:'balloon',count:5,svg:(c)=>`<svg viewBox="0 0 40 60" fill="none"><ellipse cx="20" cy="22" rx="14" ry="18" fill="${c}" opacity="0.75"/><ellipse cx="14" cy="16" rx="4" ry="5" fill="rgba(255,255,255,0.3)"/><path d="M20 40Q18 46 22 52Q20 56 20 58" stroke="${c}" stroke-width="1.5" stroke-linecap="round" opacity="0.8"/><path d="M18 40L22 40L20 43Z" fill="${c}" opacity="0.7"/></svg>`,colors:['#f48fb1','#e91e63','#f8bbd0','#ec407a','#f06292'],sizeRange:[28,50]},
{type:'petal',count:12,svg:(c)=>`<svg viewBox="0 0 24 40" fill="none"><ellipse cx="12" cy="20" rx="9" ry="16" fill="${c}" opacity="0.65"/></svg>`,colors:['#fce4ec','#f8bbd0','#f48fb1','#fff0f4'],sizeRange:[16,30]},
{type:'moon',count:3,svg:()=>`<svg viewBox="0 0 40 40" fill="none"><path d="M28 20C28 28.84 20.84 36 12 36C10.14 36 8.36 35.68 6.72 35.1C9.4 38.58 13.6 41 18.4 41C26.68 41 33.4 34.28 33.4 26C33.4 19.06 28.96 13.14 22.72 11.1C25.9 13.5 28 16.52 28 20Z" fill="#f8bbd0" opacity="0.6"/><circle cx="8" cy="8" r="1.5" fill="#f48fb1" opacity="0.5"/><circle cx="30" cy="6" r="1" fill="#f8bbd0" opacity="0.6"/></svg>`,colors:['#f8bbd0'],sizeRange:[24,40]},
{type:'gift',count:3,svg:(c)=>`<svg viewBox="0 0 40 44" fill="none"><rect x="2" y="16" width="36" height="26" rx="3" fill="${c}" opacity="0.75"/><rect x="2" y="10" width="36" height="8" rx="2" fill="${c}" opacity="0.9"/><path d="M20 10L20 42" stroke="rgba(255,255,255,0.5)" stroke-width="2"/><path d="M20 10C16 2 10 2 12 6C14 10 20 10 20 10" fill="rgba(255,255,255,0.4)"/><path d="M20 10C24 2 30 2 28 6C26 10 20 10 20 10" fill="rgba(255,255,255,0.4)"/></svg>`,colors:['#f48fb1','#e91e63','#f8bbd0'],sizeRange:[28,44]},
{type:'crown',count:3,svg:()=>`<svg viewBox="0 0 50 36" fill="none"><path d="M4 32L4 18L14 26L25 6L36 26L46 18L46 32Z" fill="url(#fg)" opacity="0.75" stroke="rgba(244,143,177,0.4)" stroke-width="1"/><circle cx="4" cy="32" r="3" fill="#f8bbd0" opacity="0.8"/><circle cx="25" cy="6" r="3" fill="#f8bbd0" opacity="0.8"/><circle cx="46" cy="32" r="3" fill="#f8bbd0" opacity="0.8"/><defs><linearGradient id="fg" x1="4" y1="6" x2="46" y2="32" gradientUnits="userSpaceOnUse"><stop offset="0%" stop-color="#fce4ec"/><stop offset="100%" stop-color="#f48fb1"/></linearGradient></defs></svg>`,colors:['#f48fb1'],sizeRange:[30,50]},
];
function initFloaters(){floatersEl.innerHTML='';floaterDefs.forEach(def=>{for(let i=0;i<def.count;i++){const el=document.createElement('div');el.className='floater';const color=def.colors[Math.floor(Math.random()*def.colors.length)];const size=def.sizeRange[0]+Math.random()*(def.sizeRange[1]-def.sizeRange[0]);const dur=10+Math.random()*14;const delay=-Math.random()*20;const left=Math.random()*100;el.style.cssText=`left:${left}%;bottom:-60px;width:${size}px;height:${size*1.2}px;--dur:${dur}s;--delay:${delay}s;`;el.innerHTML=def.svg(color);floatersEl.appendChild(el);}});}
function animateHeroEntrance(){}
ctaBtn.addEventListener('click',(e)=>{createRipple(e,ctaBtn);document.getElementById('cardSection').scrollIntoView({behavior:'smooth'});setTimeout(()=>{if(!cardFlipped)flipCard();},600);});
cardWrapper.addEventListener('click',(e)=>{createRippleAt(e.clientX,e.clientY,'rgba(244,143,177,0.35)',80);if(!cardFlipped){flipCard();}else{unflipCard();}});
function flipCard(){cardFlipped=true;card.classList.add('is-flipped');cardWrapper.classList.add('glowing');setTimeout(()=>burstConfetti(),300);setTimeout(()=>createGlowWave(cardWrapper),100);setTimeout(()=>burstParticles(cardWrapper),200);setTimeout(()=>sparkleRain(),400);setTimeout(()=>createFloatingHearts(),600);}
function unflipCard(){cardFlipped=false;card.classList.remove('is-flipped');setTimeout(()=>cardWrapper.classList.remove('glowing'),900);}
const CONFETTI_COLORS=['#e91e63','#f48fb1','#fce4ec','#f8bbd0','#c2185b','#f06292','#ffffff','#ad1457','#ff80ab','#ff4081'];
class ConfettiPiece{constructor(){this.reset(true);}reset(initial=false){this.x=Math.random()*confettiCvs.width;this.y=initial?Math.random()*confettiCvs.height*-1-10:-20;this.w=6+Math.random()*10;this.h=4+Math.random()*6;this.color=CONFETTI_COLORS[Math.floor(Math.random()*CONFETTI_COLORS.length)];this.vx=-2+Math.random()*4;this.vy=2+Math.random()*4;this.rot=Math.random()*Math.PI*2;this.rspd=-0.05+Math.random()*0.1;this.alpha=0.85+Math.random()*0.15;this.shape=Math.random()>0.4?'rect':Math.random()>0.5?'circle':'heart';this.dead=false;}update(){this.x+=this.vx;this.y+=this.vy;this.rot+=this.rspd;this.vy+=0.04;this.vx*=0.99;if(this.y>confettiCvs.height+30)this.dead=true;}draw(ctx){ctx.save();ctx.globalAlpha=this.alpha;ctx.translate(this.x,this.y);ctx.rotate(this.rot);ctx.fillStyle=this.color;if(this.shape==='rect'){ctx.fillRect(-this.w/2,-this.h/2,this.w,this.h);}else if(this.shape==='circle'){ctx.beginPath();ctx.arc(0,0,this.w/2,0,Math.PI*2);ctx.fill();}else{const s=this.w*0.08;ctx.beginPath();ctx.moveTo(0,s*3);ctx.bezierCurveTo(-s*4,-s*1,-s*8,s*5,0,s*8);ctx.bezierCurveTo(s*8,s*5,s*4,-s*1,0,s*3);ctx.fill();}ctx.restore();}}
function resizeConfettiCanvas(){confettiCvs.width=window.innerWidth;confettiCvs.height=window.innerHeight;}
function burstConfetti(){if(confettiActive)return;confettiActive=true;resizeConfettiCanvas();confettiCvs.style.display='block';confettiPcs=[];for(let i=0;i<180;i++){const p=new ConfettiPiece();p.x=confettiCvs.width*0.5+(-150+Math.random()*300);p.y=confettiCvs.height*0.35;p.vy=-6-Math.random()*8;p.vx=-5+Math.random()*10;p.alpha=1;confettiPcs.push(p);}setTimeout(()=>{for(let i=0;i<80;i++){const p=new ConfettiPiece();p.x=Math.random()*confettiCvs.width;p.y=-10;confettiPcs.push(p);}},400);function loop(){ctx.clearRect(0,0,confettiCvs.width,confettiCvs.height);confettiPcs.forEach(p=>{p.update();p.draw(ctx);});confettiPcs=confettiPcs.filter(p=>!p.dead);if(confettiPcs.length>0){animFrame=requestAnimationFrame(loop);}else{ctx.clearRect(0,0,confettiCvs.width,confettiCvs.height);confettiCvs.style.display='none';confettiActive=false;}}animFrame=requestAnimationFrame(loop);}
function createGlowWave(targetEl){const rect=targetEl.getBoundingClientRect();const wave=document.createElement('div');const cx=rect.left+rect.width/2;const cy=rect.top+rect.height/2;Object.assign(wave.style,{position:'fixed',left:cx+'px',top:cy+'px',width:'10px',height:'10px',borderRadius:'50%',background:'transparent',border:'3px solid rgba(244,143,177,0.7)',transform:'translate(-50%,-50%) scale(1)',transition:'all 0.9s cubic-bezier(0.16,1,0.3,1)',zIndex:'300',pointerEvents:'none'});document.body.appendChild(wave);requestAnimationFrame(()=>{wave.style.transform='translate(-50%,-50%) scale(60)';wave.style.opacity='0';wave.style.borderColor='rgba(244,143,177,0)';});setTimeout(()=>wave.remove(),1000);}
function burstParticles(targetEl){const rect=targetEl.getBoundingClientRect();const cx=rect.left+rect.width/2;const cy=rect.top+rect.height/2;const colors=['#f48fb1','#e91e63','#f8bbd0','#ffffff','#fce4ec','#ad1457'];for(let i=0;i<30;i++){const p=document.createElement('div');p.className='particle';const angle=(Math.PI*2/30)*i+Math.random()*0.5;const dist=60+Math.random()*120;const tx=Math.cos(angle)*dist;const ty=Math.sin(angle)*dist;const size=4+Math.random()*8;const color=colors[Math.floor(Math.random()*colors.length)];const dur=0.6+Math.random()*0.8;Object.assign(p.style,{left:cx+'px',top:cy+'px',width:size+'px',height:size+'px',background:color,'--tx':tx+'px','--ty':ty+'px','--dur':dur+'s'});document.body.appendChild(p);setTimeout(()=>p.remove(),(dur+0.1)*1000);}}
function sparkleRain(){const symbols=['✨','⭐','✦','★','✿','♡','❀'];for(let i=0;i<30;i++){setTimeout(()=>{const s=document.createElement('span');s.className='sparkle-drop';const sz=10+Math.random()*16;const dur=1.2+Math.random()*1.2;Object.assign(s.style,{left:Math.random()*100+'vw',top:(10+Math.random()*70)+'vh','--sz':sz+'px','--dur2':dur+'s','--delay2':'0s',fontSize:sz+'px'});s.textContent=symbols[Math.floor(Math.random()*symbols.length)];document.body.appendChild(s);setTimeout(()=>s.remove(),(dur+0.2)*1000);},i*60);}}
function createFloatingHearts(){const colors=['#e91e63','#f48fb1','#f8bbd0','#c2185b','#ff4081'];for(let i=0;i<12;i++){setTimeout(()=>{const h=document.createElement('div');Object.assign(h.style,{position:'fixed',left:(20+Math.random()*60)+'vw',bottom:'-60px',fontSize:(16+Math.random()*20)+'px',color:colors[Math.floor(Math.random()*colors.length)],zIndex:'500',pointerEvents:'none',opacity:'0',animation:`floatRise ${4+Math.random()*4}s ease-in-out forwards`,'--dur':(4+Math.random()*4)+'s','--delay':'0s'});h.textContent='♡';document.body.appendChild(h);setTimeout(()=>h.remove(),9000);},i*120);}}
function createRipple(e,btn){const rect=btn.getBoundingClientRect();const r=document.createElement('span');r.className='ripple';const size=Math.max(rect.width,rect.height);Object.assign(r.style,{width:size+'px',height:size+'px',left:(e.clientX-rect.left-size/2)+'px',top:(e.clientY-rect.top-size/2)+'px'});btn.appendChild(r);setTimeout(()=>r.remove(),700);}
function createRippleAt(x,y,color='rgba(244,143,177,0.4)',maxR=60){const r=document.createElement('div');Object.assign(r.style,{position:'fixed',left:x+'px',top:y+'px',width:'10px',height:'10px',borderRadius:'50%',background:color,transform:'translate(-50%,-50%) scale(1)',transition:'all 0.6s cubic-bezier(0.16,1,0.3,1)',zIndex:'400',pointerEvents:'none',opacity:'1'});document.body.appendChild(r);requestAnimationFrame(()=>{r.style.transform=`translate(-50%,-50%) scale(${maxR})`;r.style.opacity='0';});setTimeout(()=>r.remove(),650);}
const MELODY=[{note:'C4',dur:.375},{note:'C4',dur:.125},{note:'D4',dur:.5},{note:'C4',dur:.5},{note:'F4',dur:.5},{note:'E4',dur:1},{note:'C4',dur:.375},{note:'C4',dur:.125},{note:'D4',dur:.5},{note:'C4',dur:.5},{note:'G4',dur:.5},{note:'F4',dur:1},{note:'C4',dur:.375},{note:'C4',dur:.125},{note:'C5',dur:.5},{note:'A4',dur:.5},{note:'F4',dur:.5},{note:'E4',dur:.5},{note:'D4',dur:1},{note:'A4',dur:.375},{note:'A4',dur:.125},{note:'A4',dur:.5},{note:'F4',dur:.5},{note:'G4',dur:.5},{note:'F4',dur:1}];
const NOTE_FREQ={C4:261.63,D4:293.66,E4:329.63,F4:349.23,G4:392,A4:440,B4:493.88,C5:523.25};
let melodyInterval=null,melodyNodes=[];
function initAudio(){if(audioCtx)return;audioCtx=new(window.AudioContext||window.webkitAudioContext)();}
function playMelody(){if(!audioCtx)initAudio();if(audioCtx.state==='suspended')audioCtx.resume();function scheduleAll(){melodyNodes.forEach(n=>{try{n.stop();}catch(e){}});melodyNodes=[];let t=audioCtx.currentTime+0.05;const tempo=0.55;MELODY.forEach(({note,dur})=>{const osc=audioCtx.createOscillator();const gain=audioCtx.createGain();osc.connect(gain);gain.connect(audioCtx.destination);osc.type='sine';osc.frequency.setValueAtTime(NOTE_FREQ[note],t);const d=dur*tempo;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(0.18,t+0.02);gain.gain.exponentialRampToValueAtTime(0.001,t+d-0.05);osc.start(t);osc.stop(t+d);melodyNodes.push(osc);t+=d;});const total=MELODY.reduce((s,n)=>s+n.dur*tempo,0);melodyInterval=setTimeout(scheduleAll,total*1000-200);}scheduleAll();}
function stopMelody(){clearTimeout(melodyInterval);melodyInterval=null;melodyNodes.forEach(n=>{try{n.stop(audioCtx.currentTime+0.1);}catch(e){}});melodyNodes=[];}
musicBtn.addEventListener('click',()=>{musicPlaying=!musicPlaying;const on=musicBtn.querySelector('.music-icon--on');const off=musicBtn.querySelector('.music-icon--off');if(musicPlaying){playMelody();musicBtn.classList.add('is-playing');on.style.display='none';off.style.display='flex';}else{stopMelody();musicBtn.classList.remove('is-playing');on.style.display='flex';off.style.display='none';}});
const revealTargets=document.querySelectorAll('.cel-card,.celebration__heading,.celebration__quote,.card-wrapper,.section-label');
const revealObserver=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.style.opacity='1';entry.target.style.transform='translateY(0)';revealObserver.unobserve(entry.target);}});},{threshold:.15,rootMargin:'0px 0px -40px 0px'});
revealTargets.forEach((el,i)=>{el.style.opacity='0';el.style.transform='translateY(30px)';el.style.transition=`opacity 0.8s ${i*.12}s cubic-bezier(0.16,1,0.3,1),transform 0.8s ${i*.12}s cubic-bezier(0.16,1,0.3,1)`;revealObserver.observe(el);});
let lastTrailTime=0;
document.addEventListener('mousemove',(e)=>{const now=Date.now();if(now-lastTrailTime<80)return;lastTrailTime=now;const trail=document.createElement('div');const size=6+Math.random()*6;Object.assign(trail.style,{position:'fixed',left:e.clientX+'px',top:e.clientY+'px',width:size+'px',height:size+'px',borderRadius:'50%',background:`rgba(244,143,177,${.3+Math.random()*.4})`,transform:'translate(-50%,-50%) scale(1)',transition:'all 0.5s cubic-bezier(0.16,1,0.3,1)',zIndex:'9000',pointerEvents:'none'});document.body.appendChild(trail);requestAnimationFrame(()=>{trail.style.transform='translate(-50%,-50%) scale(0)';trail.style.opacity='0';});setTimeout(()=>trail.remove(),550);});
window.addEventListener('resize',()=>{if(confettiActive)resizeConfettiCanvas();});
const hero=document.getElementById('hero');let heroSparkleInterval=null;
hero.addEventListener('mouseenter',()=>{heroSparkleInterval=setInterval(()=>{const sp=document.createElement('span');const symbols=['✦','✧','⋆','*','·'];Object.assign(sp.style,{position:'fixed',left:Math.random()*100+'vw',top:Math.random()*80+'vh',fontSize:(8+Math.random()*10)+'px',color:`rgba(244,143,177,${.3+Math.random()*.7})`,pointerEvents:'none',zIndex:'5',transition:'all 1.5s ease',opacity:'0'});sp.textContent=symbols[Math.floor(Math.random()*symbols.length)];document.body.appendChild(sp);requestAnimationFrame(()=>{sp.style.opacity='1';});setTimeout(()=>{sp.style.opacity='0';},800);setTimeout(()=>sp.remove(),1600);},200);});
hero.addEventListener('mouseleave',()=>{clearInterval(heroSparkleInterval);heroSparkleInterval=null;});
cardWrapper.addEventListener('mousemove',(e)=>{if(cardFlipped)return;const rect=cardWrapper.getBoundingClientRect();const dx=(e.clientX-rect.left-rect.width/2)/(rect.width/2);const dy=(e.clientY-rect.top-rect.height/2)/(rect.height/2);card.style.transform=`rotateX(${-dy*10}deg) rotateY(${dx*10}deg)`;});
cardWrapper.addEventListener('mouseleave',()=>{if(!cardFlipped)card.style.transform='';});
document.querySelectorAll('.footer__stars span').forEach((el,i)=>{el.style.animationDelay=(i*.2)+'s';});
cardWrapper.addEventListener('touchstart',(e)=>{e.preventDefault();const t=e.touches[0];createRippleAt(t.clientX,t.clientY,'rgba(244,143,177,0.35)',60);},{passive:false});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&audioCtx){audioCtx.suspend();}else if(!document.hidden&&audioCtx&&musicPlaying){audioCtx.resume();}});
setTimeout(()=>{const welcomeSymbols=['✨','✦','★','♡'];for(let i=0;i<20;i++){setTimeout(()=>{const s=document.createElement('span');Object.assign(s.style,{position:'fixed',left:Math.random()*100+'vw',top:Math.random()*100+'vh',fontSize:(10+Math.random()*12)+'px',color:`rgba(244,143,177,${.4+Math.random()*.6})`,pointerEvents:'none',zIndex:'3',transition:'opacity 1s ease',opacity:'0'});s.textContent=welcomeSymbols[Math.floor(Math.random()*welcomeSymbols.length)];document.body.appendChild(s);requestAnimationFrame(()=>{s.style.opacity='1';});setTimeout(()=>{s.style.opacity='0';},1200);setTimeout(()=>s.remove(),2200);},(i*150)+2000);}},2400);
  
